### ISSUE TITLE
Handle invalid method request

### ISSUE THREAD

**Issue by handysama** [bsm/datadog-notifications#13]
Invalid method request raise `NoMethodError`:
```
NoMethodError:
       undefined method `[]' for nil:NilClass
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/dsl/inside_route.rb:324:in `route'
     # ./lib/datadog/notifications/plugins/grape.rb:26:in `record'
     # ./lib/datadog/notifications/plugins/grape.rb:17:in `block in initialize'
     # ./lib/datadog/notifications.rb:67:in `block in subscribe'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:127:in `finish'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:46:in `block in finish'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:46:in `each'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications/fanout.rb:46:in `finish'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:42:in `finish_with_state'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:27:in `ensure in instrument'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:27:in `instrument'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/endpoint.rb:243:in `run'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/endpoint.rb:313:in `block in build_stack'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/middleware/base.rb:31:in `call!'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/middleware/base.rb:24:in `call'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/middleware/error.rb:37:in `block in call!'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/middleware/error.rb:36:in `catch'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/middleware/error.rb:36:in `call!'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/middleware/base.rb:24:in `call'
     # /Users/handy/.rvm/gems/ruby-2.4.1@global/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/endpoint.rb:227:in `call!'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/endpoint.rb:221:in `call'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/router.rb:157:in `call_with_allow_headers'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/router.rb:112:in `transaction'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/router.rb:72:in `identity'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/router.rb:57:in `block in call'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/router.rb:135:in `with_optimization'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/router.rb:56:in `call'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/api.rb:119:in `call'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/api.rb:45:in `call!'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/api.rb:40:in `call'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/rack-test-0.8.2/lib/rack/mock_session.rb:29:in `request'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/rack-test-0.8.2/lib/rack/test.rb:251:in `process_request'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/rack-test-0.8.2/lib/rack/test.rb:129:in `custom_request'
     # /Users/handy/.rvm/gems/ruby-2.4.1/gems/rack-test-0.8.2/lib/rack/test.rb:66:in `post'
     # ./spec/datadog/notifications/plugins/grape_spec.rb:91:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Grape::Exceptions::MethodNotAllowed:
     #   405 Not Allowed
     #   /Users/handy/.rvm/gems/ruby-2.4.1/gems/grape-1.0.1/lib/grape/endpoint.rb:254:in `block in run'
```

To reproduce, just add these code to [grape_spec.rb](https://github.com/bsm/datadog-notifications/blob/master/spec/datadog/notifications/plugins/grape_spec.rb)

```
  it 'should handled invalid method' do
    post '/rescued'

    expect(last_response.status).to eq(405)
  end
```

I expect datadog should forward `Grape::Exceptions::MethodNotAllowed`. Any advice or guide to fix this?

**Comment by dim** [comment]
Thanks, fixed in 0.5.1
